name: docker image build
on:
  push:
    branches: [ "main", "uat", "developmet" ]
  pull_request: 
    branches: [ "main", "uat", "developmet" ]



jobs:
  build:
    runs-on: ubuntu:24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: docker build images
        run: docker build . --file dataarchaive/Dockerfile -t lates:$(date +%s)