name: docker image build
on:
  push:
    branches: [ "main", "uat", "developmet" ]
  pull_request: 
    branches: [ "main", "uat", "developmet" ]



jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
     
      - name: docker build images
        run: docker build . --file dataarchaive/Dockerfile -t test:${{ github.sha }}
      - name: Save the docker image
        run: |
          docker save test:${{ github.sha }} > /tmp/test:${{ github.sha }}.tar
          ls -la /tmp/
      - name: upload image on artifect
        uses: actions/upload-artifact@v4
        with:
          name: test-image
          path:  /tmp/test:${{ github.sha }}.tar
          retain-days: 2   
          if-no-files-found: error   
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
     - name: Download docker image from artifect
       uses: actions/download-artifact@v4
       with:
        name: test-image
        path: /tmp/
     - name: Set up Docker
       uses: docker/setup-buildx-action@v3
     - name: Load image
       run: docker load < /tmp/test:${{ github.sha }}.tar

     - name: visualize the image
       run: | 
          docker images
          docker ps -a
          docker run -d -p 8080:80 test:${{ github.sha }}
          docker stop $(docker ps -q)

      # - name: Checking runnning container 
      #   run: docker ps -a
      # - name: Start the container
      #   run: docker run -d -p 8080:80 test:${{ github.sha }}
      # - name:  test the container
      #   run: curl http://localhost:8080 > output.txt
      # - name: Display the output
      #   run: cat output.txt
      # - name: stop the container
      #   run: docker stop $(docker ps -q)